name_max: 50
email_max: 255
pass_min: 8
checkbox_true: "1"
avatar_size: 50
gravatar_size: 80
per_page: 10
expired: 2
img_size: 3
max_content: 140
limit_size_image: 5
byte_to_megabyte: 1048576
accepted_image_format: "image/jpeg,image/gif,image/png"
